title: "DX Tech Papers"
website: https://devpasta.github.io
basewebsite: /pages
remote_theme: "pmarsceill/just-the-docs"
color_scheme: dark

aux_links:
  "<img src='/assets/img/github.svg'/>":
    - "https://github.com/devpasta/papers"
