title: "DX Tech Papers"
remote_theme: "pmarsceill/just-the-docs"
repository: "francescobianco/dx-tech-papers"

aux_links:
  "<img src='/assets/img/github.svg'/>":
    - "https://github.com/francescobianco/dx-tech-papers"
